<a href="https://colab.research.google.com/github/Pranith1785/Algorithms/blob/master/TensorFlow_2_0_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Installing Tensorflow 2.0**

In [ ]:
!pip install tensorflow-gpu

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.5.0'

## **Constants** 

In [5]:
tensor = tf.constant([[1,2],[2,3]])

In [6]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [7]:
tensor.shape

TensorShape([2, 2])

In [9]:
## getting values of a constant
tensor.numpy()[0]

array([1, 2], dtype=int32)

## **Variables**

In [12]:
tfVariable = tf.Variable([[1.,2,3.],[4,5.0,6]])
tfVariable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [13]:
tfVariable.shape

TensorShape([2, 3])

In [14]:
## changing the value in tensor variable
tfVariable[1,2].assign(123)
tfVariable.numpy()

array([[  1.,   2.,   3.],
       [  4.,   5., 123.]], dtype=float32)

### **Operations**

In [15]:
## adding constant value to tensor variable
tensor + 23

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 25],
       [25, 26]], dtype=int32)>

In [16]:
## multiply with value
tfVariable * 8

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  8.,  16.,  24.],
       [ 32.,  40., 984.]], dtype=float32)>

### **Using Numpy**

In [17]:
np.square(tensor)

array([[1, 4],
       [4, 9]], dtype=int32)

In [18]:
np.sqrt(tfVariable)

array([[ 1.       ,  1.4142135,  1.7320508],
       [ 2.       ,  2.236068 , 11.090536 ]], dtype=float32)

In [20]:
np.dot(tensor,tensor)

array([[ 5,  8],
       [ 8, 13]], dtype=int32)

## **Strings**

In [22]:
tfString = tf.constant("Tensorflow 2.0")
tfString

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow 2.0'>

In [26]:
tf.strings.length(tfString)

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [27]:
tf.strings.split(tfString,sep=" ")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Tensorflow', b'2.0'], dtype=object)>

In [29]:
tf.strings.unicode_decode(tfString,input_encoding="UTF-8")

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119,  32,  50,  46,
        48], dtype=int32)>

In [30]:
tf_array = tf.constant(["tensorflow","keras","Deep learning","AI"])

In [31]:
for element in tf_array:
  print(element)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'keras', shape=(), dtype=string)
tf.Tensor(b'Deep learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
